services:
  mongo:
    platform: linux/amd64
    image: mongo:7.0.20
    
  rick-and-morty-api:
    platform: linux/amd64
    image: rick-and-morty-api
    build:
      dockerfile: ./Dockerfile
    ports:
      - ":8080"
    command: sh -c "npm run test:mock && npm start"
    depends_on:
      - mongo
    healthcheck:
      test: [
        "CMD", "curl", "-X", "POST", "http://localhost:8080/graphql",
        "-H", "content-type: application/json",
        "--data-raw", "{\"operationName\":null,\"variables\":{},\"query\":\"{ characters { results { id } } }\"}"
      ]
      interval: 30s
      start_period: 10s
      timeout: 10s
