services:
  gitlab-ce:
    platform: linux/amd64
    image: gitlab/gitlab-ce:17.11.0-ce.0
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_ROOT_PASSWORD: '3jAR8hK9c3cj'
    #  GITLAB_OMNIBUS_CONFIG: |
    #    # Add any other gitlab.rb configuration here, each on its own line
    #    #external_url 'https://gitlab.example.com'
    ports:
      - ':80'
    #  - '443:443'
    #  - '22:22'
#    volumes:
#      - '$GITLAB_HOME/config:/etc/gitlab'
#      - '$GITLAB_HOME/logs:/var/log/gitlab'
#      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '512m'
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost/users/sign_in | grep -q 'authenticity_token' && curl -s -f http://localhost/api/graphql > /dev/null"]
      interval: 1m
      start_period: 15m
      timeout: 10s
      retries: 5