services:
  postgres:
    platform: linux/amd64
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: travis_ci_test
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/db_init_complete"]
      interval: 30s
      start_period: 5m
      timeout: 10s
      retries: 3
    volumes:
      - ./pg_sample_data.sql:/app/dump.sql:ro
      - ./init-db.sh:/docker-entrypoint-initdb.d/01-init.sh:ro

  catalysis-hub:
    platform: linux/amd64
    image: catalysis-hub
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ":8000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f -X POST http://localhost:8000/graphql \
        -H 'Content-Type: application/json' \
        -d '{\"query\":\"{ reactions { totalCount } }\"}' > /dev/null"]
      interval: 30s
      start_period: 5m
      timeout: 10s
      retries: 3