services: 

  graphw00f:
    platform: linux/amd64
    image: graphw00f
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ../../results:/results
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["--help"]