services:
  emb-graphql-ncs:
    platform: linux/amd64
    image: emb-graphql-ncs
    build:
      dockerfile: ./Dockerfile
    ports:
      - ":8080"
    command:  ["java", "-jar", "graphql-ncs-sut.jar" ]
    healthcheck:
      test: ["CMD", "curl", "-X", "POST", "http://localhost:8080/graphql",
        "-H", "Content-Type: application/json",
        "-d", "'{\"query\":\"{ continent(code: \\\"EU\\\") { code } }\"}'"]
      interval: 30s
      start_period: 30s
      timeout: 10s
      retries: 3