services:
  db:
    platform: linux/amd64
    image: postgres:13
    environment:
      POSTGRES_DB: react-ecommerce
      POSTGRES_USER: react-ecommerce
      POSTGRES_PASSWORD: react-ecommerce

  react-ecommerce:
    platform: linux/amd64
    image: react-ecommerce
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_HOST : "db"
      DATABASE_PORT : 5432
      DATABASE_USER : "react-ecommerce"
      DATABASE_PASSWORD : "react-ecommerce"
      DATABASE_NAME : "react-ecommerce"
      SECRET: "react-ecommerce-secret"
    ports:
      - ":5000"
    healthcheck:
      test: [
        "CMD", "curl", "-X", "POST", "http://localhost:5000/graphql",
        "-H", "content-type: application/json",
        "--data-raw", "{\"query\":\"{ getAllProducts { title } }\"}"
      ]
      interval: 30s
      start_period: 2m
      timeout: 10s

