name: Validate Commit Messages

on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check commit messages
        run: |
          regex='^-\[(tool|case_study|analysis|docs|infrastructure)(/[^\]]+)?\]'
          git log origin/main..HEAD --pretty=format:%s | while read -r line; do
            if ! [[ $line =~ $regex ]]; then
              echo "Invalid commit message: $line"
              exit 1
            fi
          done